# Generated by Django 4.2.4 on 2023-08-14 21:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nro_cta', models.DecimalField(decimal_places=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('nombre', models.CharField(max_length=250)),
                ('contrasenha', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='GiroCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_giro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_nro_cta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.cuentabancaria')),
            ],
        ),
        migrations.CreateModel(
            name='DepositoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_deposito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_nro_cta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.cuentabancaria')),
            ],
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.usuariobanco'),
        ),
    ]
