# Generated by Django 4.2.4 on 2023-08-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositocuenta',
            name='id_transaccion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='girocuenta',
            name='id_transaccion',
            field=models.CharField(default='', max_length=30),
        ),
    ]
