# Generated by Django 4.2.4 on 2023-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0002_depositocuenta_id_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='sesion',
            field=models.BooleanField(default='False'),
        ),
    ]
